/**
 * Source-image compressor.
 *
 * The product photography ships as 2880×1620 PNGs (~4.5 MB each). `next/image`
 * resizes those on demand, but it still has to decode a 4.7-megapixel PNG on the
 * first request for every width/format combination — which is what made the menu
 * feel slow. This script bakes the photos down to sensibly sized WebP once, so
 * the optimizer starts from a ~40 KB file instead.
 *
 * Run it whenever photos are added or replaced:
 *
 *     npm run optimize:images
 *
 * Originals are moved to `assets-src/` (git-ignored) on the first run and read
 * from there afterwards, so re-running never re-compresses an already-compressed
 * file. The web-facing `.webp` files and the generated blur map are committed.
 */
import sharp from "sharp";
import { promises as fs } from "fs";
import path from "path";

const ROOT = path.join(import.meta.dirname, "..");

/** Largest width any layout asks for; see `deviceSizes` in next.config.js. */
const MAX_WIDTH = 1600;
const QUALITY = 80;

/** Width of the inline blur placeholder baked into the HTML. Keep it tiny. */
const BLUR_WIDTH = 8;

/** Public folder the menu links to. The URL path must stay stable. */
const PHOTO_PUBLIC_DIR = "სუში გლოვოსთვის";

const ORIGINALS_DIR = path.join(ROOT, "assets-src");
const PHOTO_SRC = path.join(ORIGINALS_DIR, "product-photos");
const PHOTO_OUT = path.join(ROOT, "public", PHOTO_PUBLIC_DIR);
const BRAND_SRC = path.join(ORIGINALS_DIR, "brand");
const BLUR_MODULE = path.join(ROOT, "src", "lib", "productImageBlur.ts");

const SOURCE_RE = /\.(png|jpe?g)$/i;

const kb = (bytes) => `${(bytes / 1024).toFixed(0)} KB`;

async function exists(p) {
  try {
    await fs.stat(p);
    return true;
  } catch {
    return false;
  }
}

/**
 * First run only: lift the heavy originals out of `public/` so they stop being
 * deployed, and keep them around as the input for future runs.
 */
async function stageOriginals(from, to, filter) {
  await fs.mkdir(to, { recursive: true });
  if (!(await exists(from))) return;
  for (const name of await fs.readdir(from)) {
    if (!filter(name)) continue;
    const target = path.join(to, name);
    if (await exists(target)) continue;
    await fs.rename(path.join(from, name), target);
    console.log(`  moved ${name} → ${path.relative(ROOT, to)}/`);
  }
}

/** True when the alpha channel is entirely opaque, i.e. it only wastes bytes. */
async function alphaIsPointless(image) {
  const { hasAlpha } = await image.metadata();
  if (!hasAlpha) return false;
  const { channels } = await image.stats();
  return channels.length > 3 && channels[3].min === 255;
}

async function compressPhotos() {
  await stageOriginals(PHOTO_OUT, PHOTO_SRC, (n) => SOURCE_RE.test(n));

  const names = (await fs.readdir(PHOTO_SRC)).filter((n) => SOURCE_RE.test(n)).sort();
  if (names.length === 0) {
    // A fresh clone has the compressed .webp files but not the originals (those
    // are git-ignored). Bail out rather than regenerating an empty blur map.
    console.log(
      `  no originals in ${path.relative(ROOT, PHOTO_SRC)} — nothing to do.\n` +
        `  Restore them from git history to re-compress at different settings.`,
    );
    return;
  }
  await fs.mkdir(PHOTO_OUT, { recursive: true });

  const blur = {};
  let before = 0;
  let after = 0;

  for (const name of names) {
    const srcPath = path.join(PHOTO_SRC, name);
    const outName = `${name.replace(SOURCE_RE, "")}.webp`;
    const input = await fs.readFile(srcPath);

    let pipeline = sharp(input).resize({ width: MAX_WIDTH, withoutEnlargement: true });
    if (await alphaIsPointless(sharp(input))) pipeline = pipeline.removeAlpha();

    const out = await pipeline.webp({ quality: QUALITY, effort: 6 }).toBuffer();
    await fs.writeFile(path.join(PHOTO_OUT, outName), out);

    const placeholder = await sharp(input)
      .resize({ width: BLUR_WIDTH })
      .webp({ quality: 25, alphaQuality: 20 })
      .toBuffer();
    // Key by the same encoded URL `productImage()` builds, so a path read back
    // from the menu store looks up without any extra normalising.
    blur[encodeURI(`/${PHOTO_PUBLIC_DIR}/${outName}`)] =
      `data:image/webp;base64,${placeholder.toString("base64")}`;

    before += input.length;
    after += out.length;
    console.log(`  ${name.padEnd(44)} ${kb(input.length).padStart(9)} → ${kb(out.length)}`);
  }

  await writeBlurModule(blur);
  console.log(
    `\n${names.length} photos: ${kb(before)} → ${kb(after)} ` +
      `(${(before / after).toFixed(0)}× smaller)`,
  );
}

async function writeBlurModule(blur) {
  const entries = Object.entries(blur)
    .map(([k, v]) => `  "${k}": "${v}",`)
    .join("\n");

  const source = `// Generated by scripts/optimize-images.mjs — do not edit by hand.
// Tiny ${BLUR_WIDTH}px-wide previews, inlined into the HTML so a card shows the
// dish's colours immediately instead of an empty box.

const BLUR_BY_PATH: Record<string, string> = {
${entries}
};

/** Blur placeholder for a product photo, or null for admin-uploaded images. */
export function blurFor(src: string | null | undefined): string | undefined {
  return (src && BLUR_BY_PATH[src]) || undefined;
}
`;
  await fs.writeFile(BLUR_MODULE, source, "utf8");
  const bytes = Buffer.byteLength(source);
  console.log(`\n  wrote ${path.relative(ROOT, BLUR_MODULE)} (${kb(bytes)})`);
}

/**
 * The seigaiha band is drawn straight into an inline <svg>, which bypasses
 * `next/image` entirely — so its source file is what the browser downloads.
 * Lossless WebP keeps the flat pattern pixel-exact at a third of the size.
 */
async function compressBrandPattern() {
  const name = "SHOGUN SHUSHI-03.png";
  await stageOriginals(path.join(ROOT, "public"), BRAND_SRC, (n) => n === name);

  const srcPath = path.join(BRAND_SRC, name);
  if (!(await exists(srcPath))) return;

  const input = await fs.readFile(srcPath);
  const out = await sharp(input).webp({ lossless: true, effort: 6 }).toBuffer();
  await fs.writeFile(path.join(ROOT, "public", name.replace(/\.png$/, ".webp")), out);
  console.log(`\n  ${name.padEnd(44)} ${kb(input.length).padStart(9)} → ${kb(out.length)} (lossless)`);
}

/**
 * The editable menu store persists image paths, so point any row that still
 * references a staged-away original at its `.webp` replacement.
 */
async function migrateMenuStore() {
  const file = path.join(process.env.MENU_DATA_DIR?.trim() || path.join(ROOT, "data"), "menu.json");
  if (!(await exists(file))) return;

  const raw = await fs.readFile(file, "utf8");
  const prefix = encodeURI(`/${PHOTO_PUBLIC_DIR}/`);
  const migrated = raw.replace(
    new RegExp(`("image":\\s*")(${prefix}[^"]+?)\\.(?:png|jpe?g)(")`, "gi"),
    "$1$2.webp$3",
  );
  if (migrated === raw) return;

  await fs.writeFile(file, migrated, "utf8");
  console.log(`\n  repointed image paths in ${path.relative(ROOT, file)}`);
}

console.log("Compressing product photos…\n");
await compressPhotos();
await compressBrandPattern();
await migrateMenuStore();
